# Generated by Django 3.1.7 on 2021-03-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_auto_20210308_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='estado',
            new_name='concluido',
        ),
    ]
